### ISSUE TITLE
creating a middleware example for validating cookie

### ISSUE THREAD

**Issue by c-nv-s** [authorizerdev/authorizer-go#3]
Just as there is a ``validate_jwt_token`` method which can be used in a middleware to protect routes unless there is a jwt token.
It would be useful if there is a ``validate_cookie`` method which could be also used in middleware to protect routes unless there is a valid session cookie.

not sure if this line is related https://github.com/authorizerdev/authorizer-go/blob/34c6220aeb6c36175b55645f744ce672080c4d85/get_session.go#L13

but I couldn't find anyway to do it currently.

**Comment by c-nv-s** [comment]
@lakhansamani should it not be possible to check cookie validity with this library?

**Comment by lakhansamani** [comment]
@c-nv-s it is possible using getSession, but there is a downside where a new cookie is returned and older one is deleted from local store. So it might not be possible to use it in pure form.

May be a better idea is to introduce a new API, validateSession and using that query it should only validate and not refresh cookie
https://github.com/authorizerdev/authorizer-go/blob/main/get_session.go

**Comment by c-nv-s** [comment]
I think the new API would make more sense because I am trying to validate and not issue a new one every time

**Comment by lakhansamani** [comment]
Okay, I will try to add that by tomorrow

**Comment by lakhansamani** [comment]
I have created github issue for same: https://github.com/authorizerdev/authorizer/issues/367

**Comment by c-nv-s** [comment]
thanks

**Comment by lakhansamani** [comment]
@c-nv-s added `validate_session` https://github.com/authorizerdev/authorizer-go/blob/main/validate_session.go

**Comment by c-nv-s** [comment]
sorry to comment on a closed ticket but this feature could really do with this addition https://github.com/authorizerdev/authorizer/issues/379

**Comment by c-nv-s** [comment]
also worth noting that the user must ``url.PathUnescape(theCookieValue)`` before passing it here https://github.com/authorizerdev/authorizer-go/blob/93f295f42bfbb0eaed8dbc12cdfdf7e4655021da/examples/validate_session.go#L23
otherwise it will return an error
